from mistralai.client import Mistral
from dotenv import load_dotenv
import os
import json

load_dotenv()  # Load environment variables from .env file

client = Mistral(api_key=os.getenv("MISTRAL_API_KEY"))

def explain_learning_path(student, roadmap):

    courses = "\n".join(
        f"- {course['title']}"
        for course in roadmap
    )

    prompt = f"""
    You are an experienced career mentor. 
    
    You are an experienced career mentor helping students choose an effective learning path.

    You will receive:
    - The student's background
    - The student's career goal
    - The student's current skills
    - A recommended learning path generated by the recommendation engine

    Your job is to explain the recommended learning path clearly and personally.

    Rules:

    1. Do not add, remove, or reorder courses.
    2. Treat the provided learning path as authoritative.
    3. Explain why each course was recommended based on:
    - The student's background
    - Their current skills
    - Their career goal
    - The course's position in the learning path
    - Any prerequisite relationships
    4. Keep explanations practical and easy for a beginner to understand.
    5. Do not invent courses, skills, prerequisites, or career information.
    6. If the provided career goal is not available in the roadmap, identify the closest matching career from the available career options.
    7. If a closest matching career is found, provide exactly one concise sentence explaining the match to the student.
    8. If no reasonable career match exists, clearly state that no suitable career path is currently available.

    Return the response in this JSON structure:

    {
    "summary": "A short explanation of the overall learning path.",
    "recommendations": [
        {
        "course_id": "course ID",
        "course_title": "course title",
        "reason": "Why this course is recommended for the student.",
        "why_now": "Why the student should take this course at this point in the path."
        }
    ],
    "career_match": {
        "original_goal": "Student's original career goal",
        "matched_career": "Closest matching career or null",
        "explanation": "One concise sentence explaining the match, or an empty string if there is no match."
    }
    }

    Return ONLY valid JSON. Do not include Markdown, code fences, or additional text.


    Student Background:
    {student.background}

    Career Goal:
    {student.goal}

    Current Skills:
    {", ".join(student.skills)}

    Recommended Learning Path:

    {json.dumps(roadmap, indent=2)}

    """

    response = client.chat.complete(
    model="ministral-3b-2512",
    messages=[
        {
            "role": "system",
            "content": "You are a learning advisor that returns valid JSON only."
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    response_format= {"type": "json_object"}
)
    return json.loads(
        response.choices[0].message.content
    )