from mistralai.client import Mistral
from dotenv import load_dotenv
import os
import json

load_dotenv()  # Load environment variables from .env file

client = Mistral(api_key=os.getenv("MISTRAL_API_KEY"))

def explain_learning_path(student, roadmap):

    roadmap_data = [
        {
            "id": course["id"],
            "title": course["title"],
            "skills": course.get("skills", []),
            "difficulty": course.get(
                "difficulty",
                "Unknown"
            ),
            "prerequisites": course.get(
                "prerequisites",
                []
            )
        }
        for course in roadmap
    ]

    prompt = f"""
You are an experienced career mentor.

Your job is to explain a learning path that has already
been generated by a deterministic recommendation engine.

Student background:
{student.background}

Career goal:
{student.goal}

Current skills:
{json.dumps(student.skills)}

Authoritative learning path:
{json.dumps(roadmap_data, indent=2)}

Important rules:

1. Do NOT add courses.
2. Do NOT remove courses.
3. Do NOT reorder courses.
4. Do NOT invent courses.
5. Do NOT invent prerequisites.
6. Treat the provided learning path as authoritative.
7. Explain why each course is useful for this student.
8. Explain why each course appears at its position in the path.
9. Consider the student's existing skills when explaining the path.
10. Keep the explanations practical and beginner-friendly.

Return ONLY valid JSON.

Use exactly this structure:

{{
    "summary": "Short explanation of the overall learning path.",
    "recommendations": [
        {{
            "course_id": "course ID",
            "course_title": "course title",
            "reason": "Why this course is useful for this student.",
            "why_now": "Why this course belongs at this point in the path."
        }}
    ]
}}
"""

    response = client.chat.complete(
        model="ministral-3b-2512",
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a career mentor. "
                    "Return valid JSON only."
                )
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        response_format={
            "type": "json_object"
        }
    )

    content = response.choices[0].message.content

    return json.loads(content)